version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: <Root_password>   # Root password for MySQL
      MYSQL_DATABASE: time_log_db       # Database to be created at startup
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  app:
    image: w13:v3
    ports:
      - "80:80"
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql-data:
